"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, LockKeyhole, MapPin, Pencil, ShieldCheck, UserRound, X } from "lucide-react";
import type { Assignment, Day, SchedulePatch } from "@/lib/domain";
import { applyAssignmentChanges, validateSchedule } from "@/lib/validator";
import { useWorkspace } from "@/components/workspace-provider";

const days: Day[] = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
const toMinutes=(v:string)=>{const [h,m]=v.slice(0,5).split(":").map(Number);return h*60+m;};
const pretty=(v:string)=>{const [h,m]=v.slice(0,5).split(":").map(Number);return `${h%12||12}:${String(m).padStart(2,"0")} ${h>=12?"PM":"AM"}`;};

export function ScheduleView() {
  const { state,currentAssignments,currentScheduleVersion,currentRulebookVersion,validation,applySchedulePatch }=useWorkspace();
  const [day,setDay]=useState<Day>("Monday");
  const [editing,setEditing]=useState<Assignment|null>(null);
  const [draft,setDraft]=useState<Assignment|null>(null);
  const [reason,setReason]=useState("");
  const [notice,setNotice]=useState("");
  const [saving,setSaving]=useState(false);
  if(!state)return null;
  const classMap=new Map(state.classes.map(x=>[x.id,x])); const sessionMap=new Map(state.sessions.map(x=>[x.id,x])); const teacherMap=new Map(state.teachers.map(x=>[x.id,x])); const roomMap=new Map(state.rooms.map(x=>[x.id,x]));
  const klass=(a:Assignment)=>classMap.get(sessionMap.get(a.sessionId)?.classId||"");
  const dayAssignments=useMemo(()=>currentAssignments.filter(a=>a.day===day).sort((a,b)=>toMinutes(a.startTime)-toMinutes(b.startTime)),[currentAssignments,day]);
  const rooms=state.rooms;
  const preview=draft?validateSchedule(state,applyAssignmentChanges(currentAssignments,draft.id,draft)):null;
  const related=editing?validation.violations.filter(v=>v.assignmentIds.includes(editing.id)):[];

  function begin(a:Assignment){setEditing(a);setDraft({...a});setReason("");setNotice("");}
  async function save(){if(!draft||!editing)return;setSaving(true);const changes:Partial<Assignment>={day:draft.day,startTime:draft.startTime,endTime:draft.endTime,teacherId:draft.teacherId,roomId:draft.roomId};const patch:SchedulePatch={id:`schedule-patch-${Date.now()}`,operation:"MOVE",assignmentId:draft.id,changes,reason:reason.trim()||`Edited ${klass(draft)?.name||draft.id}`,proposedBy:"USER"};const result=await applySchedulePatch(patch);setSaving(false);if(!result.ok){setNotice(result.error||"Change blocked.");return;}setNotice(`Saved as Schedule v${result.version}.`);setEditing(null);setDraft(null);}

  return <div className="space-y-5">
    <section className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm leading-6 text-slate-600">Every room, teacher, and dancer view is derived from these canonical assignments.</p><div className="mt-2 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-slate-950 px-3 py-1.5 font-semibold text-white">Schedule v{currentScheduleVersion}</span><span className="rounded-full border border-slate-200 bg-white px-3 py-1.5">Rulebook v{currentRulebookVersion}</span><span className={`rounded-full border px-3 py-1.5 ${validation.valid?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-red-200 bg-red-50 text-red-700"}`}>{validation.hardViolations} hard · {validation.warnings} warnings</span></div></div><div className={`rounded-xl border px-4 py-2 text-sm font-semibold ${validation.valid?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-red-200 bg-red-50 text-red-800"}`}>{validation.valid?<><CheckCircle2 className="mr-2 inline size-4"/>Valid</>:<><AlertTriangle className="mr-2 inline size-4"/>Needs repair</>}</div></section>
    <div className="flex gap-2 overflow-x-auto pb-1">{days.map(d=><button key={d} onClick={()=>setDay(d)} className={`min-h-10 shrink-0 rounded-xl px-4 text-sm font-semibold ${day===d?"bg-slate-950 text-white":"border border-slate-200 bg-white text-slate-600"}`}>{d}</button>)}</div>

    <div className="lg:hidden"><div className="space-y-3">{dayAssignments.map(a=>{const c=klass(a);return <button key={a.id} onClick={()=>begin(a)} className="w-full rounded-2xl border border-slate-200 bg-white p-4 text-left shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2">{a.locked?<LockKeyhole className="size-3.5 text-slate-500"/>:null}<h3 className="font-semibold">{c?.name||a.sessionId}</h3></div><p className="mt-1 text-sm text-slate-500">{pretty(a.startTime)}–{pretty(a.endTime)}</p></div><span className="rounded-lg bg-slate-100 px-2 py-1 text-xs font-semibold">{roomMap.get(a.roomId)?.name}</span></div><div className="mt-3 flex flex-wrap gap-3 text-xs text-slate-600"><span className="inline-flex items-center gap-1"><UserRound className="size-3.5"/>{teacherMap.get(a.teacherId)?.name}</span><span className="inline-flex items-center gap-1"><Clock3 className="size-3.5"/>{c?.durationMinutes} min</span><span>{c?.level}</span></div></button>})}{dayAssignments.length===0?<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No assignments on {day} yet.</div>:null}</div></div>

    <div className="hidden overflow-x-auto lg:block"><div className="min-w-[840px] rounded-2xl border border-slate-200 bg-white"><div className="grid grid-cols-[88px_repeat(3,1fr)] border-b border-slate-200 bg-slate-50"><div className="p-3 text-xs font-semibold text-slate-500">TIME</div>{rooms.map(r=><div key={r.id} className="border-l border-slate-200 p-3"><p className="font-semibold">{r.name}</p><p className="text-xs text-slate-500">{r.capacity?`Capacity ${r.capacity}`:"No fixed capacity"}</p></div>)}</div><div className="grid grid-cols-[88px_repeat(3,1fr)]"><div className="border-r border-slate-200 bg-slate-50">{Array.from({length:20},(_,i)=>{const total=16*60+30+i*15;return <div key={total} className="h-12 border-b border-slate-100 px-2 pt-1 text-[10px] text-slate-400">{i%2===0?pretty(`${Math.floor(total/60)}:${String(total%60).padStart(2,"0")}`):""}</div>})}</div>{rooms.map(room=><div key={room.id} className="relative min-h-[960px] border-r border-slate-200 last:border-r-0" style={{backgroundImage:"linear-gradient(to bottom,#e2e8f0 1px,transparent 1px)",backgroundSize:"100% 48px"}}>{dayAssignments.filter(a=>a.roomId===room.id).map(a=>{const c=klass(a);const top=(toMinutes(a.startTime)-(16*60+30))/15*48;const height=Math.max(44,(toMinutes(a.endTime)-toMinutes(a.startTime))/15*48);return <button key={a.id} onClick={()=>begin(a)} className={`absolute left-2 right-2 overflow-hidden rounded-xl border p-3 text-left shadow-sm ${a.locked?"border-slate-300 bg-slate-100":"border-blue-200 bg-blue-50"}`} style={{top,height}}><div className="flex items-center gap-1.5">{a.locked?<LockKeyhole className="size-3"/>:null}<span className="truncate text-sm font-semibold">{c?.name}</span></div><p className="mt-1 truncate text-xs text-slate-600">{teacherMap.get(a.teacherId)?.name} · {pretty(a.startTime)}</p></button>})}</div>)}</div></div></div>

    {!validation.valid?<section className="rounded-2xl border border-red-200 bg-red-50 p-4"><h2 className="font-semibold text-red-900">Current HARD violations</h2><div className="mt-3 space-y-2">{validation.violations.filter(v=>v.severity==="HARD").slice(0,12).map((v,i)=><div key={`${v.constraintId}-${i}`} className="rounded-xl bg-white/70 p-3 text-sm text-red-900"><strong>{v.constraintId}</strong><span className="ml-2">{v.message}</span></div>)}</div></section>:null}

    {draft&&editing?<div className="fixed inset-0 z-[70] flex items-end justify-center bg-slate-950/40 sm:items-center sm:p-6"><div className="max-h-[94vh] w-full max-w-xl overflow-y-auto rounded-t-[28px] bg-white p-5 shadow-2xl sm:rounded-[28px] sm:p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-slate-500">Assignment inspector</p><h2 className="mt-1 text-xl font-semibold">{klass(draft)?.name}</h2></div><button onClick={()=>{setEditing(null);setDraft(null)}} className="rounded-xl p-2"><X className="size-5"/></button></div>{editing.locked?<div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm text-slate-700"><LockKeyhole className="mr-2 inline size-4"/>This placement is locked. Change the governing Rulebook policy first if studio reality has changed.</div>:null}<div className="mt-5 grid gap-4">
      <div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold text-slate-600">Day<select disabled={editing.locked} value={draft.day} onChange={e=>setDraft({...draft,day:e.target.value as Day})} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm font-normal">{days.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">Room<select disabled={editing.locked} value={draft.roomId} onChange={e=>setDraft({...draft,roomId:e.target.value})} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm font-normal">{state.rooms.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label></div>
      <div className="grid grid-cols-2 gap-3"><label className="text-xs font-semibold text-slate-600">Start<input disabled={editing.locked} type="time" value={draft.startTime} onChange={e=>setDraft({...draft,startTime:e.target.value})} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3 text-sm font-normal"/></label><label className="text-xs font-semibold text-slate-600">End<input disabled={editing.locked} type="time" value={draft.endTime} onChange={e=>setDraft({...draft,endTime:e.target.value})} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3 text-sm font-normal"/></label></div>
      <label className="text-xs font-semibold text-slate-600">Teacher<select disabled={editing.locked} value={draft.teacherId} onChange={e=>setDraft({...draft,teacherId:e.target.value})} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm font-normal">{state.teachers.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>
      <div className={`rounded-xl border p-4 ${preview?.valid?"border-emerald-200 bg-emerald-50":"border-red-200 bg-red-50"}`}><div className="flex items-center gap-2 text-sm font-semibold">{preview?.valid?<ShieldCheck className="size-4 text-emerald-600"/>:<AlertTriangle className="size-4 text-red-600"/>}Proposed change validation</div><p className="mt-2 text-sm text-slate-700">{preview?.hardViolations||0} hard violation(s) · {preview?.warnings||0} warnings. A schedule move cannot be committed while it creates HARD violations.</p>{preview&&!preview.valid?<div className="mt-3 space-y-1 text-xs text-red-800">{preview.violations.filter(v=>v.severity==="HARD").slice(0,5).map((v,i)=><p key={i}>• {v.message}</p>)}</div>:null}</div>
      {related.length?<div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-semibold text-slate-600">Current findings for this assignment</p>{related.map((v,i)=><p key={i} className="mt-1 text-xs text-slate-600">• {v.message}</p>)}</div>:null}
      <label className="text-xs font-semibold text-slate-600">Reason<input disabled={editing.locked} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Why is this assignment moving?" className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3 text-sm font-normal"/></label>{notice?<p className="text-sm text-red-700">{notice}</p>:null}<div className="flex gap-2"><button onClick={()=>{setEditing(null);setDraft(null)}} className="min-h-11 flex-1 rounded-xl border border-slate-300 font-semibold">Cancel</button><button disabled={editing.locked||saving||!preview?.valid} onClick={()=>void save()} className="inline-flex min-h-11 flex-1 items-center justify-center gap-2 rounded-xl bg-slate-950 font-semibold text-white disabled:opacity-40"><Pencil className="size-4"/>{saving?"Saving…":"Save new schedule version"}</button></div>
    </div></div></div>:null}
  </div>;
}
