import { describe, expect, it } from "vitest";
import type { Assignment, StudioRule, StudioState } from "@/lib/domain";
import { validateSchedule } from "@/lib/validator";

const now="2026-08-30T00:00:00Z";
const baseRule=(partial:Partial<StudioRule>):StudioRule=>({id:"rule",category:"TEST",type:"NO_OVERLAP",title:"Rule",description:"Rule",strength:"HARD",status:"ACTIVE",verificationStatus:"VERIFIED",affectedEntityIds:[],parameters:{},exceptions:[],source:{type:"SYSTEM_SEED"},versionIntroduced:1,updatedAt:now,...partial});
const assignment=(partial:Partial<Assignment>):Assignment=>({id:"a",sessionId:"session-a",day:"Monday",startTime:"17:00",endTime:"18:00",teacherId:"teacher-cami",roomId:"room-a",locked:false,status:"NORMAL",...partial});
function state(rules:StudioRule[]=[],assignments:Assignment[]=[assignment({})]):StudioState{return{studioId:"s",studioName:"DWDE",teachers:[{id:"teacher-cami",name:"Cami",subjects:["Jazz","Tap"]},{id:"teacher-karly",name:"Karly",subjects:["Ballet"]},{id:"teacher-aimee",name:"Aimée",subjects:["Ballet"]}],rooms:[{id:"room-a",name:"Studio A",capacity:20},{id:"room-b",name:"Studio B",capacity:20}],students:[{id:"student-child",name:"Karly's daughter",level:"Level 4B"}],cohorts:[],classes:[{id:"class-a",name:"Jazz 1",subject:"Jazz",level:"Level 1",durationMinutes:60,weeklyFrequency:1,rosterStudentIds:[],eligibleTeacherIds:["teacher-cami"]},{id:"class-b",name:"Ballet 5",subject:"Ballet",level:"Level 5",durationMinutes:60,weeklyFrequency:1,rosterStudentIds:["student-child"],eligibleTeacherIds:["teacher-karly","teacher-aimee"]},{id:"class-c",name:"Ballet 4",subject:"Ballet",level:"Level 4",durationMinutes:60,weeklyFrequency:1,rosterStudentIds:[],eligibleTeacherIds:["teacher-karly","teacher-aimee"]}],sessions:[{id:"session-a",classId:"class-a",ordinal:1},{id:"session-b",classId:"class-b",ordinal:1},{id:"session-c",classId:"class-c",ordinal:1}],rules,rulebookVersions:[],ruleHistory:[],scheduleVersions:[{id:"sv",version:1,rulebookVersion:1,createdAt:now,actor:"test",reason:"test",assignments}],scenarios:[],auditEvents:[]};}

describe("DWDE deterministic validator",()=>{
  it("detects room and teacher double booking",()=>{const s=state([], [assignment({id:"a"}),assignment({id:"b",sessionId:"session-a"})]);const r=validateSchedule(s);expect(r.hardViolations).toBeGreaterThanOrEqual(2);expect(r.violations.some(v=>v.message.includes("double-booked"))).toBe(true);});
  it("enforces required room",()=>{const rule=baseRule({id:"room",type:"REQUIRED_ROOM",parameters:{required_room_id:"room-a",subject:"Ballet"}});const s=state([rule],[assignment({id:"b",sessionId:"session-b",teacherId:"teacher-aimee",roomId:"room-b"})]);expect(validateSchedule(s).violations.some(v=>v.constraintId==="room")).toBe(true);});
  it("enforces Cami maximum workdays",()=>{const rule=baseRule({id:"cami-days",type:"MAX_TEACHER_WORKDAYS",parameters:{teacher_id:"teacher-cami",max_days:4}});const days=["Monday","Tuesday","Wednesday","Thursday","Friday"] as const;const list=days.map((day,i)=>assignment({id:`a${i}`,day}));const s=state([rule],list);expect(validateSchedule(s).violations.some(v=>v.constraintId==="cami-days")).toBe(true);});
  it("enforces latest finish",()=>{const rule=baseRule({id:"finish",type:"LATEST_FINISH",parameters:{levels:["Level 1"],time:"20:30"}});const s=state([rule],[assignment({startTime:"20:00",endTime:"21:00"})]);expect(validateSchedule(s).violations.some(v=>v.constraintId==="finish")).toBe(true);});
  it("enforces no Friday for Level 5",()=>{const rule=baseRule({id:"friday",type:"NO_DAY",parameters:{levels:["Level 5"],day:"Friday"}});const s=state([rule],[assignment({sessionId:"session-b",teacherId:"teacher-aimee",day:"Friday"})]);expect(validateSchedule(s).violations.some(v=>v.constraintId==="friday")).toBe(true);});
  it("does not enforce disabled HARD rules",()=>{const rule=baseRule({id:"disabled",type:"NO_DAY",status:"DISABLED",parameters:{levels:["Level 1"],day:"Monday"}});expect(validateSchedule(state([rule])).violations.some(v=>v.constraintId==="disabled")).toBe(false);});
  it("enforces Karly/daughter arrival relationship when active",()=>{const rule=baseRule({id:"relationship",type:"RELATIONSHIP_ARRIVAL_WINDOW",parameters:{teacher_id:"teacher-karly",student_id:"student-child",minutes:15}});const list=[assignment({id:"teach",sessionId:"session-c",teacherId:"teacher-karly",startTime:"16:00",endTime:"17:00"}),assignment({id:"child",sessionId:"session-b",teacherId:"teacher-aimee",startTime:"18:00",endTime:"19:00",roomId:"room-b"})];expect(validateSchedule(state([rule],list)).violations.some(v=>v.constraintId==="relationship")).toBe(true);});
});
