"use client";

import { useState } from "react";
import { Building2, GraduationCap, Pencil, UserRound, UsersRound, X } from "lucide-react";
import type { Room, Teacher } from "@/lib/domain";
import { useWorkspace } from "@/components/workspace-provider";

export function PeopleView(){
  const {state,currentAssignments,updateTeacher,updateRoom,canEdit}=useWorkspace();
  const [tab,setTab]=useState<"TEACHERS"|"DANCERS"|"ROOMS">("TEACHERS");
  const [teacher,setTeacher]=useState<Teacher|null>(null);const [room,setRoom]=useState<Room|null>(null);const [notice,setNotice]=useState("");
  if(!state)return null;
  const sessionMap=new Map(state.sessions.map(s=>[s.id,s]));const classMap=new Map(state.classes.map(c=>[c.id,c]));
  const assignmentClass=(sessionId:string)=>classMap.get(sessionMap.get(sessionId)?.classId||"");
  const teacherAssignments=(id:string)=>currentAssignments.filter(a=>a.teacherId===id);
  const dancerAssignments=(id:string)=>currentAssignments.filter(a=>(assignmentClass(a.sessionId)?.rosterStudentIds||[]).includes(id));
  const teacherRules=(t:Teacher)=>state.rules.filter(r=>r.affectedEntityIds.includes(t.id)||r.parameters.teacher_id===t.id||`${r.title} ${r.description} ${r.category}`.toLowerCase().includes(t.name.toLowerCase()));
  async function saveTeacher(){if(!teacher)return;const r=await updateTeacher(teacher,`Updated ${teacher.name} profile metadata`);setNotice(r.ok?"Teacher profile metadata saved. Scheduling qualifications remain governed by the Rulebook.":r.error||"Save failed.");if(r.ok)setTeacher(null);}
  async function saveRoom(){if(!room)return;const r=await updateRoom(room,`Updated ${room.name}`);setNotice(r.ok?"Room saved through the governed mutation boundary.":r.error||"Save failed.");if(r.ok)setRoom(null);}

  return <div className="space-y-5"><div><p className="text-sm leading-6 text-slate-600">Schedules are derived from canonical assignments. <strong>Teacher qualification truth lives in the current Rulebook</strong>, not in the legacy subject tags on teacher profiles.</p></div>{notice?<div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm text-blue-900">{notice}</div>:null}<div className="flex gap-2 overflow-x-auto">{([['TEACHERS','Teachers',UserRound],['DANCERS','Dancers',UsersRound],['ROOMS','Rooms',Building2]] as const).map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`inline-flex min-h-10 shrink-0 items-center gap-2 rounded-xl px-4 text-sm font-semibold ${tab===id?"bg-slate-950 text-white":"border border-slate-200 bg-white text-slate-600"}`}><Icon className="size-4"/>{label}</button>)}</div>

  {tab==="TEACHERS"?<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{state.teachers.map(t=>{const assignments=teacherAssignments(t.id);const rules=teacherRules(t);return <article key={t.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between"><div><h2 className="font-semibold">{t.name}</h2><p className="mt-1 text-xs text-slate-500">{t.id}</p></div>{canEdit?<button onClick={()=>setTeacher({...t,subjects:[...t.subjects]})} className="grid size-10 place-items-center rounded-xl border border-slate-200" aria-label={`Edit ${t.name}`}><Pencil className="size-4"/></button>:null}</div><div className="mt-4"><p className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Legacy descriptive tags · not scheduling authority</p><div className="mt-2 flex flex-wrap gap-1.5">{t.subjects.map(s=><span key={s} className="rounded-lg bg-slate-100 px-2 py-1 text-xs text-slate-500">{s}</span>)}</div></div><div className="mt-4 grid grid-cols-2 gap-2 text-center text-xs"><div className="rounded-xl bg-slate-50 p-3"><strong className="block text-lg">{assignments.length}</strong>sessions</div><div className="rounded-xl bg-slate-50 p-3"><strong className="block text-lg">{new Set(assignments.map(a=>a.day)).size}</strong>workdays</div></div><p className="mt-3 text-xs text-slate-500">{rules.length} current Rulebook item{rules.length===1?"":"s"} mention or target this teacher</p></article>})}</div>:null}

  {tab==="DANCERS"?<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{state.students.map(s=>{const list=dancerAssignments(s.id).sort((a,b)=>a.day.localeCompare(b.day)||a.startTime.localeCompare(b.startTime));return <article key={s.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-slate-100"><GraduationCap className="size-5 text-slate-500"/></div><div><h2 className="font-semibold">{s.name}</h2><p className="text-xs text-slate-500">{s.level}</p></div></div><div className="mt-4 space-y-2">{list.map(a=><div key={a.id} className="rounded-xl bg-slate-50 p-3 text-xs"><p className="font-semibold">{assignmentClass(a.sessionId)?.name}</p><p className="mt-1 text-slate-500">{a.day} · {a.startTime.slice(0,5)}–{a.endTime.slice(0,5)}</p></div>)}{!list.length?<p className="text-xs text-slate-500">No scheduled classes in the current assignment set.</p>:null}</div></article>})}</div>:null}

  {tab==="ROOMS"?<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{state.rooms.map(r=>{const list=currentAssignments.filter(a=>a.roomId===r.id);return <article key={r.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between"><div><h2 className="font-semibold">{r.name}</h2><p className="mt-1 text-xs text-slate-500">Capacity {r.capacity??"not set"}</p></div>{canEdit?<button onClick={()=>setRoom({...r,features:[...(r.features||[])]})} className="grid size-10 place-items-center rounded-xl border border-slate-200" aria-label={`Edit ${r.name}`}><Pencil className="size-4"/></button>:null}</div><p className="mt-4 text-sm text-slate-600">{list.length} current assignment{list.length===1?"":"s"}</p><div className="mt-3 flex flex-wrap gap-1.5">{r.features?.map(f=><span key={f} className="rounded-lg bg-slate-100 px-2 py-1 text-xs">{f}</span>)}</div></article>})}</div>:null}

  {teacher?<div className="fixed inset-0 z-[70] flex items-end justify-center bg-slate-950/40 sm:items-center sm:p-6"><div className="w-full max-w-lg rounded-t-[28px] bg-white p-5 sm:rounded-[28px] sm:p-6"><div className="flex justify-between"><h2 className="text-xl font-semibold">Edit {teacher.name}</h2><button onClick={()=>setTeacher(null)}><X className="size-5"/></button></div><div className="mt-5 space-y-4"><label className="block text-xs font-semibold text-slate-600">Name<input value={teacher.name} onChange={e=>setTeacher({...teacher,name:e.target.value})} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3 text-sm font-normal"/></label><label className="block text-xs font-semibold text-slate-600">Notes<textarea value={teacher.notes||""} onChange={e=>setTeacher({...teacher,notes:e.target.value})} rows={4} className="mt-1 w-full rounded-xl border border-slate-300 p-3 text-sm font-normal"/></label><div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm text-blue-950"><strong>Qualifications are not edited here.</strong> Teacher availability, required/prohibited classes, subjects and levels belong in the Rulebook so they remain versioned and auditable.</div><div className="flex gap-2"><button onClick={()=>setTeacher(null)} className="min-h-11 flex-1 rounded-xl border border-slate-300 font-semibold">Cancel</button><button onClick={()=>void saveTeacher()} className="min-h-11 flex-1 rounded-xl bg-slate-950 font-semibold text-white">Save metadata</button></div></div></div></div>:null}

  {room?<div className="fixed inset-0 z-[70] flex items-end justify-center bg-slate-950/40 sm:items-center sm:p-6"><div className="w-full max-w-lg rounded-t-[28px] bg-white p-5 sm:rounded-[28px] sm:p-6"><div className="flex justify-between"><h2 className="text-xl font-semibold">Edit {room.name}</h2><button onClick={()=>setRoom(null)}><X className="size-5"/></button></div><div className="mt-5 space-y-4"><label className="block text-xs font-semibold text-slate-600">Name<input value={room.name} onChange={e=>setRoom({...room,name:e.target.value})} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3 text-sm font-normal"/></label><label className="block text-xs font-semibold text-slate-600">Capacity<input type="number" min={1} value={room.capacity??""} onChange={e=>setRoom({...room,capacity:e.target.value?Number(e.target.value):undefined})} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3 text-sm font-normal"/></label><label className="block text-xs font-semibold text-slate-600">Features<input value={(room.features||[]).join(", ")} onChange={e=>setRoom({...room,features:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3 text-sm font-normal"/></label><p className="rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-600">This update is transactional, versioned in entity history, and audited. Rules that govern room use remain separate Rulebook truth.</p><div className="flex gap-2"><button onClick={()=>setRoom(null)} className="min-h-11 flex-1 rounded-xl border border-slate-300 font-semibold">Cancel</button><button onClick={()=>void saveRoom()} className="min-h-11 flex-1 rounded-xl bg-slate-950 font-semibold text-white">Save room</button></div></div></div></div>:null}
  </div>;
}
