"use client";

import { AlertTriangle, BookOpenCheck, CalendarDays, CheckCircle2, History, ShieldCheck } from "lucide-react";
import { useWorkspace } from "@/components/workspace-provider";

export function VersionsView(){
  const {state,currentRulebookVersion,currentScheduleVersion,currentScheduleRulebookVersion,scheduleIsStale,validation}=useWorkspace();
  if(!state)return null;
  const scheduleState=scheduleIsStale?"STALE RULEBOOK":validation.hardViolations?"NEEDS REPAIR":validation.fullyValidated?"FULLY VALIDATED":"PARTIALLY VALIDATED";
  return <div className="space-y-6">
    <section className={`rounded-2xl border p-4 ${scheduleIsStale?"border-amber-200 bg-amber-50":validation.hardViolations?"border-red-200 bg-red-50":validation.fullyValidated?"border-emerald-200 bg-emerald-50":"border-blue-200 bg-blue-50"}`}><div className="flex items-start gap-3">{scheduleIsStale||validation.hardViolations?<AlertTriangle className="mt-0.5 size-5 shrink-0"/>:validation.fullyValidated?<CheckCircle2 className="mt-0.5 size-5 shrink-0"/>:<ShieldCheck className="mt-0.5 size-5 shrink-0"/>}<div><p className="text-xs font-semibold uppercase tracking-[.12em]">{scheduleState}</p><p className="mt-1 text-sm leading-6">Current Schedule v{currentScheduleVersion} is linked to Rulebook v{currentScheduleRulebookVersion}; current Rulebook is v{currentRulebookVersion}. {scheduleIsStale?"The schedule must be explicitly revalidated/rebased before another schedule mutation.":`${validation.hardViolations} detected HARD violation(s). Validator coverage is ${validation.coverage.implementedHardRules}/${validation.coverage.applicableHardRules} applicable HARD rules.`}</p></div></div></section>

    <p className="text-sm leading-6 text-slate-600">Rulebook and Schedule versions are independent immutable history. A new Rulebook version does not silently rewrite an older ScheduleVersion, and restoring or rebasing creates another version rather than erasing the trail.</p>

    <div className="grid gap-5 xl:grid-cols-2">
      <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><BookOpenCheck className="size-5 text-slate-400"/><h2 className="font-semibold">Rulebook versions</h2><span className="ml-auto rounded-full bg-slate-950 px-2.5 py-1 text-xs font-semibold text-white">current v{currentRulebookVersion}</span></div><div className="mt-4 divide-y divide-slate-100">{state.rulebookVersions.map(v=><div key={v.id} className="py-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><strong>v{v.version}</strong><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${v.status==="CURRENT"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{v.status||"HISTORICAL"}</span></div><span className="text-xs text-slate-400">{new Date(v.createdAt).toLocaleString()}</span></div><p className="mt-1 text-sm text-slate-700">{v.reason}</p><p className="mt-2 text-xs text-slate-500">{v.actor} · {v.changedRuleIds.length} rule{v.changedRuleIds.length===1?"":"s"} changed{v.parentVersion?` · parent v${v.parentVersion}`:""}</p>{v.sourceHash?<p className="mt-2 truncate text-[10px] text-slate-400">SHA-256 {v.sourceHash}</p>:null}{v.changedRuleIds.length?<div className="mt-2 flex flex-wrap gap-1">{v.changedRuleIds.slice(0,8).map(id=><span key={id} className="rounded-md bg-slate-100 px-2 py-1 text-[10px] text-slate-500">{id}</span>)}{v.changedRuleIds.length>8?<span className="rounded-md bg-slate-50 px-2 py-1 text-[10px] text-slate-400">+{v.changedRuleIds.length-8}</span>:null}</div>:null}</div>)}</div></section>

      <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><CalendarDays className="size-5 text-slate-400"/><h2 className="font-semibold">Schedule versions</h2><span className="ml-auto rounded-full bg-slate-950 px-2.5 py-1 text-xs font-semibold text-white">current v{currentScheduleVersion}</span></div><div className="mt-4 divide-y divide-slate-100">{state.scheduleVersions.map(v=>{const result=v.validationResult;const stale=v.rulebookVersion!==currentRulebookVersion;const status=v.isCurrent?(stale?"STALE":result?.fullyValidated?"FULLY VALIDATED":result?.hardViolations?"NEEDS REPAIR":"PARTIAL"):"HISTORICAL";return <div key={v.id} className="py-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><strong>Schedule v{v.version}</strong>{v.isCurrent?<span className="rounded-full bg-emerald-50 px-2 py-0.5 text-[10px] font-bold text-emerald-700">CURRENT</span>:null}</div><span className="text-xs text-slate-400">{new Date(v.createdAt).toLocaleString()}</span></div><p className="mt-1 text-sm text-slate-700">{v.reason}</p><p className="mt-2 text-xs text-slate-500">{v.actor} · linked to Rulebook v{v.rulebookVersion}</p><div className="mt-2 flex flex-wrap gap-2 text-[10px] font-semibold"><span className={`rounded-md px-2 py-1 ${status==="FULLY VALIDATED"?"bg-emerald-50 text-emerald-700":status==="NEEDS REPAIR"?"bg-red-50 text-red-700":status==="STALE"?"bg-amber-50 text-amber-800":"bg-blue-50 text-blue-700"}`}>{status}</span>{result?<span className="rounded-md bg-slate-100 px-2 py-1 text-slate-600">{result.hardViolations} detected HARD · {result.coverage.implementedHardRules}/{result.coverage.applicableHardRules} covered</span>:<span className="rounded-md bg-slate-100 px-2 py-1 text-slate-500">No stored validation snapshot</span>}</div></div>})}</div></section>
    </div>

    <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><History className="size-5 text-slate-400"/><h2 className="font-semibold">Audit trail</h2></div><div className="mt-4 grid gap-2">{state.auditEvents.slice(0,30).map(e=><div key={e.id} className="rounded-xl bg-slate-50 p-3"><div className="flex flex-wrap items-center gap-2"><span className="rounded-md bg-white px-2 py-1 text-[10px] font-bold text-slate-500">{e.action}</span><p className="text-sm font-medium text-slate-800">{e.detail}</p></div><p className="mt-1 text-xs text-slate-500">{e.actor} · {new Date(e.at).toLocaleString()}</p></div>)}</div></section>
  </div>;
}
