"use client";

import { BookOpenCheck, CalendarDays, History } from "lucide-react";
import { useWorkspace } from "@/components/workspace-provider";

export function VersionsView(){
  const {state,currentRulebookVersion,currentScheduleVersion}=useWorkspace(); if(!state)return null;
  return <div className="space-y-6"><p className="text-sm leading-6 text-slate-600">Rulebook and Schedule versions are independent. Every ScheduleVersion records the exact Rulebook version it was created against.</p><div className="grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><BookOpenCheck className="size-5 text-slate-400"/><h2 className="font-semibold">Rulebook versions</h2><span className="ml-auto rounded-full bg-slate-950 px-2.5 py-1 text-xs font-semibold text-white">current v{currentRulebookVersion}</span></div><div className="mt-4 divide-y divide-slate-100">{state.rulebookVersions.map(v=><div key={v.id} className="py-4"><div className="flex items-center justify-between"><strong>v{v.version}</strong><span className="text-xs text-slate-400">{new Date(v.createdAt).toLocaleString()}</span></div><p className="mt-1 text-sm text-slate-700">{v.reason}</p><p className="mt-2 text-xs text-slate-500">{v.actor} · {v.changedRuleIds.length} rule{v.changedRuleIds.length===1?"":"s"} changed</p>{v.changedRuleIds.length?<div className="mt-2 flex flex-wrap gap-1">{v.changedRuleIds.slice(0,8).map(id=><span key={id} className="rounded-md bg-slate-100 px-2 py-1 text-[10px] text-slate-500">{id}</span>)}</div>:null}</div>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><CalendarDays className="size-5 text-slate-400"/><h2 className="font-semibold">Schedule versions</h2><span className="ml-auto rounded-full bg-slate-950 px-2.5 py-1 text-xs font-semibold text-white">current v{currentScheduleVersion}</span></div><div className="mt-4 divide-y divide-slate-100">{state.scheduleVersions.map(v=><div key={v.id} className="py-4"><div className="flex items-center justify-between"><strong>Schedule v{v.version}</strong><span className="text-xs text-slate-400">{new Date(v.createdAt).toLocaleString()}</span></div><p className="mt-1 text-sm text-slate-700">{v.reason}</p><p className="mt-2 text-xs text-slate-500">{v.actor} · validated against Rulebook v{v.rulebookVersion}</p></div>)}</div></section></div><section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><History className="size-5 text-slate-400"/><h2 className="font-semibold">Audit trail</h2></div><div className="mt-4 grid gap-2">{state.auditEvents.slice(0,30).map(e=><div key={e.id} className="rounded-xl bg-slate-50 p-3"><div className="flex flex-wrap items-center gap-2"><span className="rounded-md bg-white px-2 py-1 text-[10px] font-bold text-slate-500">{e.action}</span><p className="text-sm font-medium text-slate-800">{e.detail}</p></div><p className="mt-1 text-xs text-slate-500">{e.actor} · {new Date(e.at).toLocaleString()}</p></div>)}</div></section></div>;
}
