import type { RecentChange, ScheduleAssignment, StudioRule } from "@/lib/types";

export const ruleCategories = [
  "Studio Operations",
  "Rooms",
  "Teachers",
  "Dancers / Cohorts",
  "Classes",
  "Sequencing",
  "Attendance",
  "Timing",
  "Capacity",
  "Company",
  "Preferences",
  "Assumptions",
  "Exceptions",
] as const;

export const rules: StudioRule[] = [
  {
    id: "R-ROOM-004",
    title: "Ballet Levels 1–5 require Studio A",
    description: "Ballet Levels 1 through 5 must be scheduled in Studio A because the Marley flooring is required for these classes.",
    strength: "HARD",
    category: "Rooms",
    relatedEntities: ["Studio A", "Ballet 1", "Ballet 2", "Ballet 3", "Ballet 4A", "Ballet 4B/5", "Ballet 5"],
    status: "VERIFIED",
    source: "Owner interview",
    lastModified: "Aug 28, 2026",
    versionIntroduced: "v3",
    reason: "Marley flooring requirement.",
  },
  {
    id: "R-ROOM-005",
    title: "Pointe and Pre-Pointe require Studio A",
    description: "All Pointe and Pre-Pointe sessions require Studio A and should not be moved to Studios B or C.",
    strength: "HARD",
    category: "Rooms",
    relatedEntities: ["Studio A", "Pre-Pointe", "Pointe 1", "Pointe 2/3"],
    status: "VERIFIED",
    source: "Owner interview",
    lastModified: "Aug 28, 2026",
    versionIntroduced: "v3",
  },
  {
    id: "R-TEACH-011",
    title: "Cami maximum regular workdays",
    description: "Cami may teach regular Monday–Saturday classes on no more than four days because Sunday company work counts as a fifth workday.",
    strength: "HARD",
    category: "Teachers",
    relatedEntities: ["Cami", "Monday–Saturday", "Sunday Company"],
    status: "VERIFIED",
    source: "Cami confirmation",
    lastModified: "Aug 30, 2026",
    versionIntroduced: "v3",
  },
  {
    id: "R-TEACH-012",
    title: "Cami cannot teach Hip Hop",
    description: "Do not assign Hip Hop classes to Cami.",
    strength: "HARD",
    category: "Teachers",
    relatedEntities: ["Cami", "Hip Hop"],
    status: "VERIFIED",
    source: "Teacher qualification list",
    lastModified: "Aug 27, 2026",
    versionIntroduced: "v2",
  },
  {
    id: "R-TEACH-013",
    title: "Cami cannot teach Elementary 1",
    description: "Elementary 1 classes must be assigned to another qualified teacher.",
    strength: "HARD",
    category: "Teachers",
    relatedEntities: ["Cami", "Elementary 1"],
    status: "VERIFIED",
    source: "Teacher qualification list",
    lastModified: "Aug 27, 2026",
    versionIntroduced: "v2",
  },
  {
    id: "R-TEACH-030",
    title: "Karly cannot teach Tap or Hip Hop",
    description: "Karly may not be assigned to Tap or Hip Hop classes.",
    strength: "HARD",
    category: "Teachers",
    relatedEntities: ["Karly", "Tap", "Hip Hop"],
    status: "VERIFIED",
    source: "Teacher qualification list",
    lastModified: "Aug 27, 2026",
    versionIntroduced: "v2",
  },
  {
    id: "R-REL-001",
    title: "Karly and daughter arrival relationship",
    description: "Karly's teaching assignments must remain compatible with the arrival timing required for her daughter's scheduled classes.",
    strength: "HARD",
    category: "Dancers / Cohorts",
    relatedEntities: ["Karly", "Karly's daughter"],
    status: "NEEDS_REVIEW",
    source: "Scheduling interview",
    lastModified: "Aug 30, 2026",
    versionIntroduced: "v3",
  },
  {
    id: "R-GAP-001",
    title: "Teacher gaps cannot exceed one hour",
    description: "A teacher's gap between regular classes on the same day should not exceed 60 minutes.",
    strength: "HARD",
    category: "Timing",
    relatedEntities: ["All teachers", "Same-day schedule"],
    status: "VERIFIED",
    source: "Studio scheduling policy",
    lastModified: "Aug 25, 2026",
    versionIntroduced: "v1",
  },
  {
    id: "R-GAP-002",
    title: "Student gaps cannot exceed one hour",
    description: "A dancer's gap between required classes on the same attendance day cannot exceed 60 minutes.",
    strength: "HARD",
    category: "Attendance",
    relatedEntities: ["All dancers", "Same-day schedule"],
    status: "VERIFIED",
    source: "Studio scheduling policy",
    lastModified: "Aug 25, 2026",
    versionIntroduced: "v1",
  },
  {
    id: "R-TIME-001",
    title: "Elementary 1 must finish by 7:00 PM",
    description: "Elementary 1 sessions must end no later than 7:00 PM.",
    strength: "HARD",
    category: "Timing",
    relatedEntities: ["Elementary 1", "7:00 PM"],
    status: "VERIFIED",
    source: "Owner interview",
    lastModified: "Aug 28, 2026",
    versionIntroduced: "v3",
  },
  {
    id: "R-TIME-002",
    title: "Elementary 2 and Levels 1–2 finish by 8:30 PM",
    description: "Elementary 2 and Levels 1–2 must end no later than 8:30 PM.",
    strength: "HARD",
    category: "Timing",
    relatedEntities: ["Elementary 2", "Level 1", "Level 2", "8:30 PM"],
    status: "VERIFIED",
    source: "Owner interview",
    lastModified: "Aug 28, 2026",
    versionIntroduced: "v3",
  },
  {
    id: "R-CAP-003",
    title: "Studio C prefers a 15-dancer maximum",
    description: "Studio C normally has a preferred maximum of 15 dancers. Elementary classes may exceed this preference when needed.",
    strength: "VERY_STRONG",
    category: "Capacity",
    relatedEntities: ["Studio C", "Elementary classes", "15 dancers"],
    status: "NEEDS_REVIEW",
    source: "Owner interview",
    lastModified: "Aug 30, 2026",
    versionIntroduced: "v3",
  },
  {
    id: "R-SEQ-001",
    title: "Jazz 1 directly precedes Lyrical 1",
    description: "Jazz 1 must be directly followed by Lyrical 1 with no gap between the sessions.",
    strength: "HARD",
    category: "Sequencing",
    relatedEntities: ["Jazz 1", "Lyrical 1"],
    status: "VERIFIED",
    source: "Class sequencing requirement",
    lastModified: "Aug 29, 2026",
    versionIntroduced: "v3",
  },
  {
    id: "R-SEQ-002",
    title: "Jazz 3 directly precedes Contemporary 3",
    description: "Jazz 3 must be directly followed by Contemporary 3 with no gap between the sessions.",
    strength: "HARD",
    category: "Sequencing",
    relatedEntities: ["Jazz 3", "Contemporary 3"],
    status: "VERIFIED",
    source: "Class sequencing requirement",
    lastModified: "Aug 29, 2026",
    versionIntroduced: "v3",
  },
  {
    id: "R-SEQ-010",
    title: "Ballet 3 has one designated Pre-Pointe follow-on",
    description: "One designated weekly Ballet 3 meeting must be directly followed by Pre-Pointe.",
    strength: "HARD",
    category: "Sequencing",
    relatedEntities: ["Ballet 3", "Pre-Pointe"],
    status: "VERIFIED",
    source: "Class sequencing requirement",
    lastModified: "Aug 29, 2026",
    versionIntroduced: "v3",
  },
  {
    id: "R-DAY-004",
    title: "Levels 4B and 5 cannot attend Friday",
    description: "Do not schedule required Level 4B or Level 5 classes on Friday.",
    strength: "HARD",
    category: "Attendance",
    relatedEntities: ["Level 4B", "Level 5", "Friday"],
    status: "VERIFIED",
    source: "Dancer availability policy",
    lastModified: "Aug 28, 2026",
    versionIntroduced: "v3",
  },
  {
    id: "R-FIX-001",
    title: "Denise's current classes are fixed in Studio B",
    description: "Denise's current class assignments are locked to their existing times and Studio B placements unless the rulebook is explicitly changed.",
    strength: "HARD",
    category: "Classes",
    relatedEntities: ["Denise", "Studio B", "Current classes"],
    status: "VERIFIED",
    source: "Owner directive",
    lastModified: "Aug 30, 2026",
    versionIntroduced: "v3",
  },
  {
    id: "R-PREF-006",
    title: "Prefer Aimée/Karly Ballet split",
    description: "When multiple valid arrangements exist, prefer a balanced Ballet teaching split between Aimée and Karly.",
    strength: "VERY_STRONG",
    category: "Preferences",
    relatedEntities: ["Aimée", "Karly", "Ballet"],
    status: "VERIFIED",
    source: "Owner preference",
    lastModified: "Aug 29, 2026",
    versionIntroduced: "v3",
  },
];

export const mondayAssignments: ScheduleAssignment[] = [
  { id: "A-MON-001", className: "Ballet 3", teacher: "Aimée", day: "Monday", room: "Studio A", startTime: "4:45 PM", endTime: "6:15 PM", level: "Level 3", status: ["NORMAL"], enrollment: 14, rules: ["R-ROOM-004", "R-SEQ-010"] },
  { id: "A-MON-002", className: "Pre-Pointe", teacher: "Aimée", day: "Monday", room: "Studio A", startTime: "6:15 PM", endTime: "6:45 PM", level: "Level 3", status: ["LOCKED"], enrollment: 10, rules: ["R-ROOM-005", "R-SEQ-010"] },
  { id: "A-MON-003", className: "Ballet 4B/5", teacher: "Aimée", day: "Monday", room: "Studio A", startTime: "6:45 PM", endTime: "8:30 PM", level: "Levels 4B/5", status: ["NORMAL"], enrollment: 13, rules: ["R-ROOM-004", "R-DAY-004", "R-PREF-006"] },
  { id: "A-MON-004", className: "Jazz 1", teacher: "Cami", day: "Monday", room: "Studio B", startTime: "4:45 PM", endTime: "5:30 PM", level: "Level 1", status: ["NORMAL"], enrollment: 12, rules: ["R-TEACH-011", "R-SEQ-001"] },
  { id: "A-MON-005", className: "Lyrical 1", teacher: "Cami", day: "Monday", room: "Studio B", startTime: "5:30 PM", endTime: "6:15 PM", level: "Level 1", status: ["NORMAL"], enrollment: 12, rules: ["R-TEACH-011", "R-SEQ-001"] },
  { id: "A-MON-006", className: "Adult Tap", teacher: "Denise", day: "Monday", room: "Studio B", startTime: "6:30 PM", endTime: "7:30 PM", level: "Adult", status: ["LOCKED"], enrollment: 9, rules: ["R-FIX-001"] },
  { id: "A-MON-007", className: "Adult Jazz", teacher: "Denise", day: "Monday", room: "Studio B", startTime: "7:30 PM", endTime: "8:30 PM", level: "Adult", status: ["LOCKED"], enrollment: 11, rules: ["R-FIX-001"] },
  { id: "A-MON-008", className: "Elementary Jazz 1", teacher: "Sydni", day: "Monday", room: "Studio C", startTime: "4:45 PM", endTime: "5:30 PM", level: "Elementary 1", status: ["NORMAL"], enrollment: 17, rules: ["R-TIME-001", "R-CAP-003"] },
  { id: "A-MON-009", className: "Elementary Ballet 2", teacher: "Sydni", day: "Monday", room: "Studio C", startTime: "5:30 PM", endTime: "6:30 PM", level: "Elementary 2", status: ["WARNING"], enrollment: 18, rules: ["R-CAP-003", "R-TIME-002"] },
  { id: "A-MON-010", className: "Jazz 3", teacher: "Cami", day: "Monday", room: "Studio C", startTime: "6:45 PM", endTime: "7:30 PM", level: "Level 3", status: ["NORMAL"], enrollment: 15, rules: ["R-TEACH-011", "R-SEQ-002"] },
  { id: "A-MON-011", className: "Contemporary 3", teacher: "Cami", day: "Monday", room: "Studio C", startTime: "7:30 PM", endTime: "8:15 PM", level: "Level 3", status: ["NORMAL"], enrollment: 15, rules: ["R-TEACH-011", "R-SEQ-002"] },
];

export const recentChanges: RecentChange[] = [
  { title: "Studio C Elementary capacity clarified", detail: "Elementary classes may exceed the normal preferred 15-dancer limit.", timestamp: "Today, 2:42 PM", actor: "Cami" },
  { title: "Aimée Tuesday availability added", detail: "Availability window added to the working rulebook for schedule review.", timestamp: "Today, 11:18 AM", actor: "Cami" },
  { title: "Ballet 5 frequency updated", detail: "Weekly frequency changed from two sessions to three.", timestamp: "Yesterday, 4:09 PM", actor: "Cami + ChatGPT" },
];
