create or replace function public.update_teacher_record(p_teacher_id text,p_name text,p_notes text,p_reason text,p_expected_updated_at timestamptz default null)
returns jsonb language plpgsql security definer set search_path=''
as $$ declare ctx jsonb:=private.resolve_dwde_actor(); v_uid uuid:=nullif(ctx->>'user_id','')::uuid; v_studio uuid:=(ctx->>'studio_id')::uuid; v_actor text:=ctx->>'actor'; v_before jsonb; v_after jsonb; begin select to_jsonb(t) into v_before from public.teachers t where studio_id=v_studio and id=p_teacher_id for update; if v_before is null then raise exception 'Teacher not found'; end if; if p_expected_updated_at is not null and (v_before->>'updated_at')::timestamptz<>p_expected_updated_at then raise exception 'Teacher changed since this editor opened'; end if; update public.teachers set name=p_name,notes=p_notes,updated_at=now() where studio_id=v_studio and id=p_teacher_id; select to_jsonb(t) into v_after from public.teachers t where studio_id=v_studio and id=p_teacher_id; insert into public.audit_events(studio_id,actor_user_id,actor_label,action,entity_type,entity_id,detail,payload) values(v_studio,v_uid,v_actor,'TEACHER_UPDATE','TEACHER',p_teacher_id,p_reason,jsonb_build_object('before',v_before,'after',v_after)); return v_after; end $$;
create or replace function public.update_room_record(p_room_id text,p_name text,p_capacity integer,p_features text[],p_reason text,p_expected_updated_at timestamptz default null)
returns jsonb language plpgsql security definer set search_path=''
as $$ declare ctx jsonb:=private.resolve_dwde_actor(); v_uid uuid:=nullif(ctx->>'user_id','')::uuid; v_studio uuid:=(ctx->>'studio_id')::uuid; v_actor text:=ctx->>'actor'; v_before jsonb; v_after jsonb; begin select to_jsonb(t) into v_before from public.rooms t where studio_id=v_studio and id=p_room_id for update; if v_before is null then raise exception 'Room not found'; end if; if p_expected_updated_at is not null and (v_before->>'updated_at')::timestamptz<>p_expected_updated_at then raise exception 'Room changed since this editor opened'; end if; update public.rooms set name=p_name,capacity=p_capacity,features=coalesce(p_features,'{}'),updated_at=now() where studio_id=v_studio and id=p_room_id; select to_jsonb(t) into v_after from public.rooms t where studio_id=v_studio and id=p_room_id; insert into public.audit_events(studio_id,actor_user_id,actor_label,action,entity_type,entity_id,detail,payload) values(v_studio,v_uid,v_actor,'ROOM_UPDATE','ROOM',p_room_id,p_reason,jsonb_build_object('before',v_before,'after',v_after)); return v_after; end $$;
create or replace function public.update_class_identity(p_class_id text,p_name text,p_subject text,p_level text,p_reason text,p_expected_updated_at timestamptz default null)
returns jsonb language plpgsql security definer set search_path=''
as $$ declare ctx jsonb:=private.resolve_dwde_actor(); v_uid uuid:=nullif(ctx->>'user_id','')::uuid; v_studio uuid:=(ctx->>'studio_id')::uuid; v_actor text:=ctx->>'actor'; v_before jsonb; v_after jsonb; begin select to_jsonb(t) into v_before from public.class_definitions t where studio_id=v_studio and id=p_class_id for update; if v_before is null then raise exception 'Class not found'; end if; if p_expected_updated_at is not null and (v_before->>'updated_at')::timestamptz<>p_expected_updated_at then raise exception 'Class changed since this editor opened'; end if; update public.class_definitions set name=p_name,subject=p_subject,level=p_level,updated_at=now() where studio_id=v_studio and id=p_class_id; select to_jsonb(t) into v_after from public.class_definitions t where studio_id=v_studio and id=p_class_id; insert into public.audit_events(studio_id,actor_user_id,actor_label,action,entity_type,entity_id,detail,payload) values(v_studio,v_uid,v_actor,'CLASS_UPDATE','CLASS',p_class_id,p_reason,jsonb_build_object('before',v_before,'after',v_after)); return v_after; end $$;

create or replace function public.create_scenario_record(p_name text,p_base_rulebook_version integer,p_base_schedule_version integer,p_rule_patches jsonb default '[]',p_schedule_patches jsonb default '[]')
returns jsonb language plpgsql security definer set search_path=''
as $$ declare ctx jsonb:=private.resolve_dwde_actor(); v_uid uuid:=nullif(ctx->>'user_id','')::uuid; v_studio uuid:=(ctx->>'studio_id')::uuid; v_rb int; v_sv int; v_id uuid; begin select version into v_rb from public.rulebook_versions where studio_id=v_studio and status='CURRENT'; select version into v_sv from public.schedule_versions where studio_id=v_studio and is_current; if v_rb<>p_base_rulebook_version or v_sv<>p_base_schedule_version then raise exception 'Scenario base versions are stale'; end if; insert into public.scenarios(studio_id,name,base_rulebook_version,base_schedule_version,rule_patches,schedule_patches,created_by) values(v_studio,p_name,v_rb,v_sv,coalesce(p_rule_patches,'[]'),coalesce(p_schedule_patches,'[]'),v_uid) returning id into v_id; return jsonb_build_object('scenarioId',v_id); end $$;

create or replace function public.record_ai_proposal(p_proposal_type text,p_request_text text,p_response_text text,p_patch jsonb default null,p_impact jsonb default null)
returns jsonb language plpgsql security definer set search_path=''
as $$ declare v_uid uuid:=auth.uid(); v_studio uuid; v_id uuid; begin if v_uid is null then raise exception 'Authentication required'; end if; select studio_id into v_studio from public.studio_members where user_id=v_uid limit 1; if v_studio is null then raise exception 'Studio membership required'; end if; if p_proposal_type not in ('RULE_PATCH','SCHEDULE_PATCH','QUESTION') then raise exception 'Invalid proposal type'; end if; insert into public.ai_proposals(studio_id,user_id,proposal_type,request_text,response_text,patch,impact,status) values(v_studio,v_uid,p_proposal_type,p_request_text,p_response_text,p_patch,p_impact,'PROPOSED') returning id into v_id; return jsonb_build_object('proposalId',v_id); end $$;
