-- Reviewed V2 importer executes as one checked transaction. It is not exposed in normal production UI.
create or replace function public.import_reviewed_rulebook(p_package jsonb,p_reason text default 'Reviewed Rulebook import',p_source_file_sha256 text default null)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare
  v_uid uuid:=auth.uid(); v_studio uuid; v_actor text; v_incoming_version integer; v_parent_version integer;
  v_existing_same jsonb; v_rulebook_id text; v_rulebook_name text; v_rules_hash text; v_rule_count integer;
  v_reviewed_count integer; v_approved_count integer; v_edited_count integer; v_bad_count integer; v_duplicate_count integer;
  v_removed_ids text[]:='{}'; v_changed_ids text[]:='{}'; v_new_ids text[]:='{}'; v_updated_ids text[]:='{}'; v_unchanged_ids text[]:='{}';
  item jsonb; v_before jsonb; v_after jsonb; v_history_before jsonb; v_classification text; v_enforcement text;
  v_existing_type text; v_existing_parameters jsonb; v_existing_affected text[]; v_existing_exceptions jsonb; v_existing_version_introduced integer; v_is_same boolean;
begin
  if v_uid is null then raise exception 'Authentication required'; end if;
  select m.studio_id into v_studio from public.studio_members m where m.user_id=v_uid and m.role in ('OWNER','EDITOR') order by case m.role when 'OWNER' then 0 else 1 end limit 1;
  if v_studio is null then raise exception 'Editor membership required'; end if;
  if jsonb_typeof(p_package)<>'object' or p_package->>'format_version'<>'2.0' or p_package->>'document_type'<>'DWDE_SITE_RULEBOOK' then raise exception 'Reviewed Rulebook requires DWDE_SITE_RULEBOOK format 2.0'; end if;
  if jsonb_typeof(p_package->'rulebook')<>'object' or jsonb_typeof(p_package->'rules')<>'array' then raise exception 'Rulebook metadata and rules array are required'; end if;
  v_rulebook_id:=p_package#>>'{rulebook,id}'; v_rulebook_name:=p_package#>>'{rulebook,name}'; v_incoming_version:=nullif(p_package#>>'{rulebook,version}','')::integer; v_rules_hash:=lower(p_package#>>'{rulebook,rules_sha256}');
  v_rule_count:=jsonb_array_length(p_package->'rules'); v_reviewed_count:=coalesce((p_package#>>'{rulebook,reviewed_rules}')::integer,0); v_approved_count:=coalesce((p_package#>>'{rulebook,approved_without_edit}')::integer,0); v_edited_count:=coalesce((p_package#>>'{rulebook,edited_and_approved}')::integer,0);
  if v_rulebook_id<>'dwde-2026-2027-master-rulebook' or v_incoming_version<>2 or p_package#>>'{rulebook,status}'<>'REVIEWED' then raise exception 'Unexpected reviewed Rulebook authority metadata'; end if;
  if coalesce((p_package#>>'{rulebook,total_rules}')::integer,-1)<>v_rule_count or v_rule_count<>178 or v_reviewed_count<>178 or v_approved_count<>162 or v_edited_count<>16 then raise exception 'Reviewed V2 counts do not match 178/178 reviewed, 162 approved, 16 edited'; end if;
  if v_rules_hash is null or v_rules_hash!~'^[0-9a-f]{64}$' then raise exception 'Valid rules SHA-256 required'; end if;
  if p_source_file_sha256 is null or lower(p_source_file_sha256)!~'^[0-9a-f]{64}$' then raise exception 'Valid source file SHA-256 required'; end if;
  select count(*) into v_duplicate_count from (select x->>'id' id from jsonb_array_elements(p_package->'rules') x group by x->>'id' having count(*)>1)d; if v_duplicate_count>0 then raise exception 'Duplicate stable rule IDs in import'; end if;
  select count(*) into v_bad_count from jsonb_array_elements(p_package->'rules') x where coalesce(x->>'id','')!~'^[A-Z0-9]+-[0-9]{3}$' or coalesce(x->>'category','')='' or coalesce(x->>'classification','')='' or coalesce(x->>'title','')='' or not(x?'text') or coalesce(x->>'status','')='' or x->>'review_status'<>'VERIFIED' or jsonb_typeof(x->'review')<>'object' or jsonb_typeof(x->'source')<>'object' or coalesce((x#>>'{review,verified}')::boolean,false) is not true or x#>>'{review,decision}' not in ('APPROVED','EDIT');
  if v_bad_count>0 then raise exception '% reviewed rule records are invalid',v_bad_count; end if;
  select count(*) into v_bad_count from jsonb_array_elements(p_package->'rules') x where x#>>'{review,decision}'='EDIT' and(coalesce(x#>>'{review,original_text}','')='' or coalesce(x#>>'{review,correction_raw}','')=''); if v_bad_count>0 then raise exception '% edited rules lack review history',v_bad_count; end if;
  perform pg_advisory_xact_lock(hashtextextended(v_studio::text,0));
  select to_jsonb(rv) into v_existing_same from public.rulebook_versions rv where rv.studio_id=v_studio and rv.version=2 limit 1;
  if v_existing_same is not null then if lower(coalesce(v_existing_same->>'source_hash',''))=v_rules_hash then return jsonb_build_object('version',2,'ruleCount',178,'alreadyImported',true,'sourceHash',v_rules_hash,'sourceFileHash',v_existing_same->>'source_file_hash'); end if; raise exception 'Rulebook V2 already exists with a different fingerprint'; end if;
  select max(version) into v_parent_version from public.rulebook_versions where studio_id=v_studio; if coalesce(v_parent_version,0)>=2 then raise exception 'Incoming V2 cannot follow current Rulebook V%',v_parent_version; end if;
  select coalesce(p.display_name,u.email,'Studio user') into v_actor from auth.users u left join public.profiles p on p.id=u.id where u.id=v_uid;
  select coalesce(array_agg(r.id order by r.id),'{}'::text[]) into v_removed_ids from public.rules r where r.studio_id=v_studio and not exists(select 1 from jsonb_array_elements(p_package->'rules') x where x->>'id'=r.id);
  for item in select value from jsonb_array_elements(p_package->'rules') loop
    select to_jsonb(r),r.type,r.parameters,r.affected_entity_ids,r.exceptions,r.version_introduced into v_before,v_existing_type,v_existing_parameters,v_existing_affected,v_existing_exceptions,v_existing_version_introduced from public.rules r where r.studio_id=v_studio and r.id=item->>'id';
    v_classification:=item->>'classification'; v_enforcement:=case when v_classification<>'HARD' then 'NOT_APPLICABLE' when item->>'id' in('OPS-008','OPS-009','OPS-010','OPS-017','CUR-005') then 'IMPLEMENTED' else 'NOT_IMPLEMENTED' end;
    insert into public.rules(id,studio_id,category,type,title,description,strength,status,verification_status,affected_entity_ids,parameters,exceptions,source,version_introduced,updated_at,classification_raw,review_status,review,source_raw,enforcement_status)
    values(item->>'id',v_studio,item->>'category',v_existing_type,item->>'title',item->>'text',private.normalized_strength_for_classification(v_classification),item->>'status',item->>'review_status',coalesce(v_existing_affected,'{}'),coalesce(v_existing_parameters,'{}'),coalesce(v_existing_exceptions,'[]'),jsonb_build_object('type','IMPORT','document',v_rulebook_name,'version',2,'fingerprint',v_rules_hash),coalesce(v_existing_version_introduced,2),now(),v_classification,item->>'review_status',item->'review',item->'source',v_enforcement)
    on conflict(id) do update set studio_id=excluded.studio_id,category=excluded.category,title=excluded.title,description=excluded.description,strength=excluded.strength,status=excluded.status,verification_status=excluded.verification_status,source=excluded.source,updated_at=now(),classification_raw=excluded.classification_raw,review_status=excluded.review_status,review=excluded.review,source_raw=excluded.source_raw,enforcement_status=case when public.rules.type is not null and public.rules.enforcement_status in('IMPLEMENTED','PARTIAL') then public.rules.enforcement_status else excluded.enforcement_status end;
    select to_jsonb(r) into v_after from public.rules r where r.studio_id=v_studio and r.id=item->>'id';
    v_is_same:=v_before is not null and coalesce(v_before->>'description','')=item->>'text' and coalesce(v_before->>'classification_raw',replace(v_before->>'strength','_',' '))=v_classification;
    if v_before is null then v_new_ids:=array_append(v_new_ids,item->>'id'); elsif v_is_same then v_unchanged_ids:=array_append(v_unchanged_ids,item->>'id'); else v_updated_ids:=array_append(v_updated_ids,item->>'id'); end if; v_changed_ids:=array_append(v_changed_ids,item->>'id');
    v_history_before:=v_before; if v_history_before is null and item#>>'{review,decision}'='EDIT' then v_history_before:=jsonb_build_object('id',item->>'id','studio_id',v_studio,'category',item->>'category','type',null,'title',item->>'title','description',item#>>'{review,original_text}','strength',private.normalized_strength_for_classification(v_classification),'classification_raw',v_classification,'status',item->>'status','verification_status','UNVERIFIED','review_status','UNVERIFIED','affected_entity_ids','[]'::jsonb,'parameters','{}'::jsonb,'exceptions','[]'::jsonb,'source',item->'source','source_raw',item->'source','review',jsonb_build_object('decision','DRAFT_BEFORE_REVIEW','verified',false,'original_text',item#>>'{review,original_text}'),'enforcement_status','NOT_IMPLEMENTED','version_introduced',coalesce(v_parent_version,1)); end if;
    insert into public.rule_history(studio_id,rule_id,rulebook_version,actor_user_id,actor_label,reason,before_rule,after_rule,ai_proposed) values(v_studio,item->>'id',2,v_uid,v_actor,case when item#>>'{review,decision}'='EDIT' then 'Human review correction: '||(item#>>'{review,correction_raw}') else p_reason end,v_history_before,v_after,false);
  end loop;
  if cardinality(v_removed_ids)>0 then insert into public.rule_history(studio_id,rule_id,rulebook_version,actor_user_id,actor_label,reason,before_rule,after_rule,ai_proposed) select v_studio,r.id,2,v_uid,v_actor,'Superseded by reviewed DWDE Rulebook V2',to_jsonb(r),null,false from public.rules r where r.studio_id=v_studio and r.id=any(v_removed_ids); delete from public.rules where studio_id=v_studio and id=any(v_removed_ids); end if;
  if exists(select 1 from jsonb_array_elements(p_package->'rules') x where x->>'id'='DATA-001' and x->>'text'='Aimee is the correct canonical spelling of the teacher name.') then update public.teachers set name='Aimee',updated_at=now() where studio_id=v_studio and id='teacher-aimee'; end if;
  if exists(select 1 from jsonb_array_elements(p_package->'rules') x where x->>'id'='DATA-007' and x->>'text'='The canonical class entity name is Contemporary/Lyrical 3.') then update public.class_definitions set name='Contemporary/Lyrical 3',updated_at=now() where studio_id=v_studio and id='class-contemporary-3'; end if;
  if exists(select 1 from jsonb_array_elements(p_package->'rules') x where x->>'id'='REV-001' and position('not COMPANY ONLY' in x->>'text')>0) then update public.class_definitions set company_only=false,updated_at=now() where studio_id=v_studio and lower(name)='tap 1'; end if;
  update public.rulebook_versions set status='HISTORICAL' where studio_id=v_studio and status='CURRENT';
  insert into public.rulebook_versions(studio_id,version,name,actor_user_id,actor_label,reason,changed_rule_ids,snapshot,rulebook_id,status,imported_at,source_hash,source_file_hash,rule_count,parent_version,format_version,document_type,source_metadata)
  select v_studio,2,v_rulebook_name||' v2',v_uid,v_actor,p_reason,v_changed_ids||v_removed_ids,coalesce(jsonb_agg(to_jsonb(r) order by r.id),'[]'),v_rulebook_id,'CURRENT',now(),v_rules_hash,lower(p_source_file_sha256),178,v_parent_version,'2.0','DWDE_SITE_RULEBOOK',jsonb_build_object('rulebook',p_package->'rulebook','schema_notes',p_package->'schema_notes','review_summary',p_package->'review_summary') from public.rules r where r.studio_id=v_studio;
  insert into public.audit_events(studio_id,actor_user_id,actor_label,action,entity_type,detail,payload) values(v_studio,v_uid,v_actor,'REVIEWED_RULEBOOK_IMPORT','RULEBOOK',p_reason,jsonb_build_object('version',2,'rulebookId',v_rulebook_id,'rulesHash',v_rules_hash,'sourceFileHash',lower(p_source_file_sha256),'ruleCount',178,'new',v_new_ids,'updated',v_updated_ids,'unchanged',v_unchanged_ids,'superseded',v_removed_ids));
  return jsonb_build_object('version',2,'ruleCount',(select count(*) from public.rules where studio_id=v_studio),'reviewedCount',178,'approvedCount',162,'editedCount',16,'newRuleIds',v_new_ids,'updatedRuleIds',v_updated_ids,'unchangedRuleIds',v_unchanged_ids,'supersededRuleIds',v_removed_ids,'sourceHash',v_rules_hash,'sourceFileHash',lower(p_source_file_sha256),'alreadyImported',false);
end $$;
revoke execute on function public.import_canonical_rulebook(jsonb,text) from public,anon,authenticated;
grant execute on function public.import_canonical_rulebook(jsonb,text) to service_role;
revoke execute on function public.import_reviewed_rulebook(jsonb,text,text) from public,anon;
grant execute on function public.import_reviewed_rulebook(jsonb,text,text) to authenticated;
