-- Versioned Rulebook mutation with optimistic concurrency and no ability to self-certify machine enforcement.
drop function if exists public.apply_rule_patch(text,text,jsonb,text,boolean);
create function public.apply_rule_patch(p_operation text,p_rule_id text,p_changes jsonb,p_reason text,p_ai_proposed boolean default false,p_expected_rulebook_version integer default null)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare ctx jsonb:=private.resolve_dwde_actor(); v_uid uuid:=nullif(ctx->>'user_id','')::uuid; v_studio uuid:=(ctx->>'studio_id')::uuid; v_actor text:=ctx->>'actor'; v_before jsonb; v_after jsonb; v_version integer; v_id text:=coalesce(p_rule_id,p_changes->>'id'); v_prev public.rulebook_versions%rowtype; v_raw text; v_normalized text; v_enforcement text;
begin
  if v_id is null or btrim(v_id)='' then raise exception 'Stable rule id is required'; end if;
  if v_id !~ '^[A-Z0-9]+-[0-9]{3}$' then raise exception 'Invalid stable rule id'; end if;
  perform pg_advisory_xact_lock(hashtextextended(v_studio::text,0));
  select * into v_prev from public.rulebook_versions where studio_id=v_studio and status='CURRENT' order by version desc limit 1;
  if p_expected_rulebook_version is not null and coalesce(v_prev.version,0)<>p_expected_rulebook_version then raise exception 'Stale Rulebook version: expected %, current %',p_expected_rulebook_version,coalesce(v_prev.version,0); end if;
  select coalesce(max(version),0)+1 into v_version from public.rulebook_versions where studio_id=v_studio;
  select to_jsonb(r) into v_before from public.rules r where r.studio_id=v_studio and r.id=v_id;
  if p_operation='CREATE' then
    if v_before is not null then raise exception 'Rule % already exists',v_id; end if;
    v_raw:=coalesce(p_changes->>'classificationRaw',replace(p_changes->>'strength','_',' '),'MODERATE'); v_normalized:=private.normalized_strength_for_classification(v_raw); v_enforcement:=case when v_raw='HARD' then 'NOT_IMPLEMENTED' else 'NOT_APPLICABLE' end;
    insert into public.rules(id,studio_id,category,type,title,description,strength,status,verification_status,affected_entity_ids,parameters,exceptions,source,version_introduced,updated_at,classification_raw,review_status,review,source_raw,enforcement_status)
    values(v_id,v_studio,coalesce(p_changes->>'category','GENERAL'),nullif(p_changes->>'type',''),coalesce(p_changes->>'title','Untitled rule'),coalesce(p_changes->>'description',''),v_normalized,coalesce(p_changes->>'status','ACTIVE'),coalesce(p_changes->>'verificationStatus',p_changes->>'reviewStatus','UNVERIFIED'),coalesce(array(select jsonb_array_elements_text(p_changes->'affectedEntityIds')),'{}'),coalesce(p_changes->'parameters','{}'),coalesce(p_changes->'exceptions','[]'),jsonb_build_object('type',case when p_ai_proposed then 'AI_PROPOSAL_APPROVED' else 'USER_EDIT' end,'note',p_reason),v_version,now(),v_raw,coalesce(p_changes->>'reviewStatus',p_changes->>'verificationStatus','UNVERIFIED'),coalesce(p_changes->'review','{}'),coalesce(p_changes->'sourceRaw','{}'),v_enforcement);
  else
    if v_before is null then raise exception 'Rule % does not exist',v_id; end if;
    v_raw:=case when p_changes?'classificationRaw' then p_changes->>'classificationRaw' when p_changes?'strength' then replace(p_changes->>'strength','_',' ') else v_before->>'classification_raw' end; v_normalized:=private.normalized_strength_for_classification(v_raw);
    v_enforcement:=case when (p_changes ?| array['description','classificationRaw','strength','type','parameters','affectedEntityIds','exceptions']) and v_before->>'enforcement_status'='IMPLEMENTED' then 'PARTIAL' else v_before->>'enforcement_status' end;
    update public.rules set category=case when p_changes?'category' then p_changes->>'category' else category end,type=case when p_changes?'type' then nullif(p_changes->>'type','') else type end,title=case when p_changes?'title' then p_changes->>'title' else title end,description=case when p_changes?'description' then p_changes->>'description' else description end,strength=v_normalized,classification_raw=v_raw,status=case when p_operation='RETIRE' then 'RETIRED' when p_operation='DISABLE' then 'DISABLED' when p_operation='ENABLE' then 'ACTIVE' when p_changes?'status' then p_changes->>'status' else status end,verification_status=case when p_changes?'verificationStatus' then p_changes->>'verificationStatus' when p_changes?'reviewStatus' then p_changes->>'reviewStatus' else verification_status end,review_status=case when p_changes?'reviewStatus' then p_changes->>'reviewStatus' when p_changes?'verificationStatus' then p_changes->>'verificationStatus' else review_status end,review=case when p_changes?'review' then p_changes->'review' else review end,affected_entity_ids=case when p_changes?'affectedEntityIds' then array(select jsonb_array_elements_text(p_changes->'affectedEntityIds')) else affected_entity_ids end,parameters=case when p_changes?'parameters' then p_changes->'parameters' else parameters end,exceptions=case when p_changes?'exceptions' then p_changes->'exceptions' else exceptions end,enforcement_status=v_enforcement,source=jsonb_build_object('type',case when p_ai_proposed then 'AI_PROPOSAL_APPROVED' else 'USER_EDIT' end,'note',p_reason,'parentRulebookVersion',coalesce(v_prev.version,v_version-1)),updated_at=now() where studio_id=v_studio and id=v_id;
  end if;
  select to_jsonb(r) into v_after from public.rules r where r.studio_id=v_studio and r.id=v_id;
  insert into public.rule_history(studio_id,rule_id,rulebook_version,actor_user_id,actor_label,reason,before_rule,after_rule,ai_proposed) values(v_studio,v_id,v_version,v_uid,v_actor,p_reason,v_before,v_after,p_ai_proposed);
  update public.rulebook_versions set status='HISTORICAL' where studio_id=v_studio and status='CURRENT';
  insert into public.rulebook_versions(studio_id,version,name,actor_user_id,actor_label,reason,changed_rule_ids,snapshot,rulebook_id,status,rule_count,parent_version,format_version,document_type,source_metadata)
  select v_studio,v_version,'DWDE Rulebook v'||v_version,v_uid,v_actor,p_reason,array[v_id],coalesce(jsonb_agg(to_jsonb(r) order by r.id),'[]'),coalesce(v_prev.rulebook_id,'dwde-2026-2027-master-rulebook'),'CURRENT',count(*)::integer,coalesce(v_prev.version,v_version-1),'2.0','DWDE_SITE_RULEBOOK',jsonb_build_object('provenance',case when p_ai_proposed then 'AI_PROPOSAL_APPROVED' else 'USER_EDIT' end,'parentSourceHash',v_prev.source_hash) from public.rules r where r.studio_id=v_studio;
  insert into public.audit_events(studio_id,actor_user_id,actor_label,action,entity_type,entity_id,detail,payload) values(v_studio,v_uid,v_actor,'RULE_'||p_operation,'RULE',v_id,p_reason,jsonb_build_object('before',v_before,'after',v_after,'version',v_version));
  return jsonb_build_object('ruleId',v_id,'version',v_version,'before',v_before,'after',v_after);
end $$;
