-- Reconstructable DWDE production schema baseline.
-- Schema/functions only. Reviewed Rulebook and studio business data are imported application data.
-- This is a bootstrap snapshot, NOT a historical migration. Do not apply it to an existing production project.
create extension if not exists pgcrypto with schema extensions;
create extension if not exists supabase_vault;
create schema if not exists private;

create table if not exists public.studios(id uuid primary key default gen_random_uuid(),slug text not null unique,name text not null,created_at timestamptz not null default now());
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,display_name text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.studio_members(studio_id uuid not null references public.studios(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role text not null check(role in ('OWNER','EDITOR','VIEWER')),created_at timestamptz not null default now(),primary key(studio_id,user_id));
create table if not exists public.teachers(id text primary key,studio_id uuid not null references public.studios(id) on delete cascade,name text not null,subjects text[] not null default '{}',notes text,updated_at timestamptz not null default now());
create table if not exists public.rooms(id text primary key,studio_id uuid not null references public.studios(id) on delete cascade,name text not null,capacity integer,features text[] not null default '{}',updated_at timestamptz not null default now());
create table if not exists public.students(id text primary key,studio_id uuid not null references public.studios(id) on delete cascade,name text not null,level text not null,cohort_ids text[] not null default '{}',updated_at timestamptz not null default now());
create table if not exists public.cohorts(id text primary key,studio_id uuid not null references public.studios(id) on delete cascade,name text not null,student_ids text[] not null default '{}',updated_at timestamptz not null default now());
create table if not exists public.class_definitions(id text primary key,studio_id uuid not null references public.studios(id) on delete cascade,name text not null,subject text not null,level text not null,duration_minutes integer not null check(duration_minutes>0),weekly_frequency integer not null default 1 check(weekly_frequency>0),roster_student_ids text[] not null default '{}',eligible_teacher_ids text[] not null default '{}',company_only boolean not null default false,updated_at timestamptz not null default now());
create table if not exists public.class_sessions(id text primary key,studio_id uuid not null references public.studios(id) on delete cascade,class_id text not null references public.class_definitions(id) on delete cascade,ordinal integer not null default 1,locked boolean not null default false,updated_at timestamptz not null default now());
create table if not exists public.rules(id text primary key,studio_id uuid not null references public.studios(id) on delete cascade,category text not null,type text,title text not null,description text not null,strength text check(strength is null or strength in ('HARD','VERY_STRONG','MODERATE','LIGHT','BASELINE')),status text not null check(status in ('ACTIVE','NEEDS_REVIEW','DISABLED','RETIRED')),verification_status text not null check(verification_status in ('VERIFIED','NEEDS_REVIEW','UNVERIFIED')),affected_entity_ids text[] not null default '{}',parameters jsonb not null default '{}',exceptions jsonb not null default '[]',source jsonb not null default '{}',version_introduced integer not null default 1,updated_at timestamptz not null default now(),classification_raw text not null,review_status text not null check(review_status in ('VERIFIED','NEEDS_REVIEW','UNVERIFIED')),review jsonb not null default '{}',source_raw jsonb not null default '{}',enforcement_status text not null default 'NOT_IMPLEMENTED' check(enforcement_status in ('IMPLEMENTED','PARTIAL','NOT_IMPLEMENTED','NOT_APPLICABLE')));
create table if not exists public.rulebook_versions(id uuid primary key default gen_random_uuid(),studio_id uuid not null references public.studios(id) on delete cascade,version integer not null,name text not null,created_at timestamptz not null default now(),actor_user_id uuid references auth.users(id) on delete set null,actor_label text not null,reason text not null,changed_rule_ids text[] not null default '{}',snapshot jsonb not null default '[]',rulebook_id text,status text not null default 'HISTORICAL' check(status in ('CURRENT','HISTORICAL')),imported_at timestamptz,source_hash text,source_file_hash text,rule_count integer,parent_version integer,format_version text,document_type text,source_metadata jsonb not null default '{}',unique(studio_id,version));
create unique index if not exists one_current_rulebook_version_per_studio on public.rulebook_versions(studio_id) where status='CURRENT';
create table if not exists public.rule_history(id uuid primary key default gen_random_uuid(),studio_id uuid not null references public.studios(id) on delete cascade,rule_id text not null,rulebook_version integer not null,changed_at timestamptz not null default now(),actor_user_id uuid references auth.users(id) on delete set null,actor_label text not null,reason text not null,before_rule jsonb,after_rule jsonb,ai_proposed boolean not null default false);
create table if not exists public.schedule_versions(id uuid primary key default gen_random_uuid(),studio_id uuid not null references public.studios(id) on delete cascade,version integer not null,rulebook_version integer not null,created_at timestamptz not null default now(),actor_user_id uuid references auth.users(id) on delete set null,actor_label text not null,reason text not null,is_current boolean not null default false,validation_result jsonb,unique(studio_id,version));
create unique index if not exists one_current_schedule_per_studio on public.schedule_versions(studio_id) where is_current;
create table if not exists public.assignments(schedule_version_id uuid not null references public.schedule_versions(id) on delete cascade,id text not null,studio_id uuid not null references public.studios(id) on delete cascade,session_id text not null references public.class_sessions(id),day text not null check(day in ('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday')),start_time time not null,end_time time not null,teacher_id text not null references public.teachers(id),room_id text not null references public.rooms(id),locked boolean not null default false,status text not null default 'NORMAL' check(status in ('NORMAL','WARNING','AI_PROPOSED')),primary key(schedule_version_id,id));
create table if not exists public.scenarios(id uuid primary key default gen_random_uuid(),studio_id uuid not null references public.studios(id) on delete cascade,name text not null,base_rulebook_version integer not null,base_schedule_version integer not null,rule_patches jsonb not null default '[]',schedule_patches jsonb not null default '[]',created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.ai_proposals(id uuid primary key default gen_random_uuid(),studio_id uuid not null references public.studios(id) on delete cascade,user_id uuid references auth.users(id) on delete set null,proposal_type text not null check(proposal_type in ('RULE_PATCH','SCHEDULE_PATCH','QUESTION')),status text not null default 'PROPOSED' check(status in ('PROPOSED','APPLIED','REJECTED')),request_text text not null,response_text text,patch jsonb,impact jsonb,created_at timestamptz not null default now(),resolved_at timestamptz);
create table if not exists public.audit_events(id uuid primary key default gen_random_uuid(),studio_id uuid not null references public.studios(id) on delete cascade,actor_user_id uuid references auth.users(id) on delete set null,actor_label text not null,action text not null,entity_type text not null,entity_id text,detail text not null,payload jsonb,created_at timestamptz not null default now());
create table if not exists public.entity_versions(id uuid primary key default gen_random_uuid(),studio_id uuid not null references public.studios(id) on delete cascade,entity_type text not null,entity_id text not null,changed_at timestamptz not null default now(),actor_user_id uuid references auth.users(id) on delete set null,actor_label text not null,reason text not null,before_data jsonb,after_data jsonb);
create table if not exists public.studio_invites(id uuid primary key default gen_random_uuid(),studio_id uuid not null references public.studios(id) on delete cascade,email text not null,role text not null check(role in ('OWNER','EDITOR','VIEWER')),invited_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),accepted_at timestamptz,unique(studio_id,email));
create table if not exists private.user_ai_credentials(user_id uuid primary key references auth.users(id) on delete cascade,provider text not null default 'openrouter' check(provider='openrouter'),vault_secret_id uuid not null,key_hint text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table private.user_ai_credentials enable row level security;
revoke all on private.user_ai_credentials from public,anon,authenticated;

create or replace function private.normalized_strength_for_classification(p_classification text) returns text language sql immutable set search_path='' as $$ select case upper(btrim(coalesce(p_classification,''))) when 'HARD' then 'HARD' when 'VERY STRONG' then 'VERY_STRONG' when 'MODERATE' then 'MODERATE' when 'LIGHT' then 'LIGHT' when 'BASELINE' then 'BASELINE' else null end $$;

create or replace function public.admin_get_user_ai_credential_status(p_user_id uuid) returns table(configured boolean,key_hint text,updated_at timestamptz) language sql stable security definer set search_path='' as $$ select true,c.key_hint,c.updated_at from private.user_ai_credentials c where c.user_id=p_user_id and c.provider='openrouter' union all select false,null::text,null::timestamptz where not exists(select 1 from private.user_ai_credentials c where c.user_id=p_user_id and c.provider='openrouter') limit 1 $$;
create or replace function public.admin_get_user_openrouter_key(p_user_id uuid) returns text language sql stable security definer set search_path='' as $$ select v.decrypted_secret from private.user_ai_credentials c join vault.decrypted_secrets v on v.id=c.vault_secret_id where c.user_id=p_user_id and c.provider='openrouter' limit 1 $$;
create or replace function public.admin_save_user_openrouter_key(p_user_id uuid,p_key text) returns table(key_hint text,updated_at timestamptz) language plpgsql security definer set search_path='' as $$ declare v_key text:=btrim(p_key);v_secret_id uuid;v_hint text;begin if p_user_id is null then raise exception 'User ID is required';end if;if length(v_key)<20 or length(v_key)>500 then raise exception 'OpenRouter API key length is invalid';end if;v_hint:=left(v_key,8)||'••••'||right(v_key,4);select c.vault_secret_id into v_secret_id from private.user_ai_credentials c where c.user_id=p_user_id and c.provider='openrouter';if v_secret_id is null then v_secret_id:=vault.create_secret(v_key,'dwde-openrouter-'||p_user_id::text,'DWDE Studio Scheduler OpenRouter credential');insert into private.user_ai_credentials(user_id,provider,vault_secret_id,key_hint) values(p_user_id,'openrouter',v_secret_id,v_hint);else perform vault.update_secret(v_secret_id,v_key,'dwde-openrouter-'||p_user_id::text,'DWDE Studio Scheduler OpenRouter credential');update private.user_ai_credentials set key_hint=v_hint,updated_at=now() where user_id=p_user_id and provider='openrouter';end if;return query select c.key_hint,c.updated_at from private.user_ai_credentials c where c.user_id=p_user_id and c.provider='openrouter';end $$;
create or replace function public.admin_delete_user_openrouter_key(p_user_id uuid) returns boolean language plpgsql security definer set search_path='' as $$ declare v_secret_id uuid;begin select c.vault_secret_id into v_secret_id from private.user_ai_credentials c where c.user_id=p_user_id and c.provider='openrouter';if v_secret_id is null then return false;end if;delete from private.user_ai_credentials where user_id=p_user_id and provider='openrouter';delete from vault.secrets where id=v_secret_id;return true;end $$;
revoke execute on function public.admin_get_user_ai_credential_status(uuid),public.admin_get_user_openrouter_key(uuid),public.admin_save_user_openrouter_key(uuid,text),public.admin_delete_user_openrouter_key(uuid) from public,anon,authenticated;
grant execute on function public.admin_get_user_ai_credential_status(uuid),public.admin_get_user_openrouter_key(uuid),public.admin_save_user_openrouter_key(uuid,text),public.admin_delete_user_openrouter_key(uuid) to service_role;

insert into public.studios(id,slug,name) values('11111111-1111-4111-8111-111111111111','dwde','DWDE Studio') on conflict(id) do nothing;

alter table public.studios enable row level security;alter table public.profiles enable row level security;alter table public.studio_members enable row level security;alter table public.studio_invites enable row level security;alter table public.teachers enable row level security;alter table public.rooms enable row level security;alter table public.students enable row level security;alter table public.cohorts enable row level security;alter table public.class_definitions enable row level security;alter table public.class_sessions enable row level security;alter table public.rules enable row level security;alter table public.rulebook_versions enable row level security;alter table public.rule_history enable row level security;alter table public.schedule_versions enable row level security;alter table public.assignments enable row level security;alter table public.scenarios enable row level security;alter table public.ai_proposals enable row level security;alter table public.audit_events enable row level security;alter table public.entity_versions enable row level security;
